# frozen_string_literal: true

module Types
  class UserType < BaseObject
    field :id, String, null: false, method: :uuid
    field :email, String, null: true
    field :account, Types::AccountType, null: false
    field :customer, Types::CustomerType, null: true
    field :autogenerated, Boolean, null: false
  end
end
