# frozen_string_literal: true

module Types
  class User < BaseObject
    field :id, String, null: false, method: :uuid
    field :email, String, null: true
    field :name, String, null: false
    field :role, String, null: false
    field :phone, String, null: true
    field :cart, Types::Cart, null: true
    field :account, Types::Account, null: false
    field :autogenerated, Boolean, null: false
  end
end
