# frozen_string_literal: true

require 'rails_helper'

RSpec.describe User do
  it_behaves_like 'uuidable'

  it { is_expected.to belong_to :account }
  it { is_expected.to have_many :addresses }
  it { is_expected.to have_many :comments }
  it { is_expected.to have_one(:invoice_address).class_name('Address') }

  it { is_expected.to validate_presence_of :role }
  it { is_expected.to validate_presence_of :email }
  it { is_expected.to validate_presence_of :account_id }

  it { should define_enum_for(:role).with(%i[customer admin manager]) }

  describe '.for_comment' do
    let(:account) { create(:account) }
    let(:user) { create(:user, account: account) }
    let(:email) { user.email }

    subject { described_class.for_comment(email, account) }
    context 'when email belongs to a user' do
      it { is_expected.to eql user }
      it { expect(subject.autogenerated).to be false }
      it { expect(subject.account).to eql account }
    end

    context 'when email is new' do
      let(:email) { 'brand@new.email' }

      it { expect(subject.valid?).to be true }
      it { expect(subject.email).to eql email }
      it { expect(subject.role).to eql 'customer' }
      it { expect(subject.autogenerated).to be true }
      it { expect(subject.account).to eql account }
    end

    context 'when email belongs to another account' do
      let(:user) { create(:user) }

      it { expect(subject.valid?).to be true }
      it { expect(subject.email).to eql email }
      it { expect(subject.role).to eql 'customer' }
      it { expect(subject.autogenerated).to be true }
      it { expect(subject.account).to eql account }
    end
  end
end
